name: ServerSignsCommandConverter
version: ${project.version}
main: me.prosl3nderman.serversignscommandconverter.ServerSignsCommandConverter
depend: [ServerSigns]
commands:
  sscc:
    description: Server Signs Commands Converter command.